#!/bin/sh
# Remove working files from last run.
#
USAGE="
# USAGE ############## USAGE ############## USAGE ############## USAGE ##############
# Clean up all the outputs of latex commands.
# Two scenarios: given a dir or given a file                                        #
# If a dir is given, all the outputs with certain extension will be cleaned out     #
# If a file name is given, all the files with certain extensions will be cleaned out#
#####################################################################################
"
if [ $# -gt 0 ]; then
    input="${BASH_ARGV[0]}"
else
    input='.'
fi

if [ -d "$input" ]; then
    MAIN_SRC="$input/*"
elif [ -f "$input" ]; then
    MAIN_SRC=${input%.*}
elif [ -f "$input.tex" ]; then
    MAIN_SRC=${input}
else
    echo "Specify valid source file or directory"
    exit 1
fi

echo "Cleaning up latex output files: $MAIN_SRC.log etc..."

rm -f "$MAIN_SRC.log" \
       "$MAIN_SRC.aux" \
       "$MAIN_SRC.bbl" \
       "$MAIN_SRC.blg" \
       "$MAIN_SRC.dvi" \
       "$MAIN_SRC.idx" \
       "$MAIN_SRC.ilg" \
       "$MAIN_SRC.ind" \
       "$MAIN_SRC.lof" \
       "$MAIN_SRC.lot" \
       "$MAIN_SRC.ps" \
       "$MAIN_SRC.out" \
       "$MAIN_SRC.brf" \
       "$MAIN_SRC.pdf" \
       "$MAIN_SRC.toc"   2>/dev/null
