#!/bin/sh
# Remove working files from last run.
#

if [ $# -gt 0 ]; then
    MAIN_SRC=${1%.*}
else
    echo "specify the main source file name"
    exit 1
fi

echo "Removing all the latex output files with the base of $MAIN_SRC"

rm -f $MAIN_SRC.log \
       $MAIN_SRC.aux \
       $MAIN_SRC.bbl \
       $MAIN_SRC.blg \
       $MAIN_SRC.dvi \
       $MAIN_SRC.idx \
       $MAIN_SRC.ilg \
       $MAIN_SRC.ind \
       $MAIN_SRC.lof \
       $MAIN_SRC.lot \
       $MAIN_SRC.ps \
       $MAIN_SRC.out \
       $MAIN_SRC.brf \
       $MAIN_SRC.pdf \
       $MAIN_SRC.toc   2>/dev/null
