#!/bin/sh
#
USAGE="
# USAGE ############## USAGE ############## USAGE ############## USAGE ##############
# A Bourne shell script file to compile the latex template.                         #
# LIMITATIONS: the file names cannot contain space and must has extension names     #
#####################################################################################
"
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_DIR=$(realpath "$(dirname "$0")")
if [ $# -gt 0 ]; then
    MAIN_SRC="${BASH_ARGV[0]}"
elif [ `ls -l *.tex|wc -l` -eq 1 ]; then
    filename=`ls *.tex`
    MAIN_SRC="${filename%.*}"
else
    echo "You have to specify the main source file '*.tex'"
    exit 11
fi

if [ -f "$MAIN_SRC" ]; then
    MAIN_SRC=${MAIN_SRC%.*}
elif [ -f "$MAIN_SRC.tex" ]; then
    MAIN_SRC="$MAIN_SRC"
else
    echo "Specify a valid source file name"
    exit 1
fi

echo "$SCRIPT_DIR/LatexClean $MAIN_SRC"

cmd="'tell app \"Preview\" to close document \"$MAIN_SRC.pdf\"'"
echo $cmd| xargs osascript -e
$SCRIPT_DIR/LatexClean $MAIN_SRC

# Clear the screen.
#
clear

# Run latex, bibtex, and makeindex to create the output file
#
echo ""
echo "    First run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 2
    fi

if [ -e $MAIN_SRC.bib ]; then
    echo ""
    echo "    Run of BibTeX ..."
    echo ""
    bibtex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        break
    fi

    echo ""
    echo "    Second run of LaTeX ..."
    echo ""
    pdflatex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 4
    fi
    echo ""
    echo "    Third run of LaTeX ..."
    echo ""
    pdflatex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 5
    fi
fi
if [ -e $MAIN_SRC.idx ]; then
    echo ""
    echo "    Run of makeindex ..."
    echo ""
    makeindex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 6
    fi
    echo ""
    echo "    Fourth run of LaTeX ..."
    echo ""
    pdflatex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 7
    fi
    echo ""
    echo "    Fifth and last run of LaTeX ..."
    echo ""
    pdflatex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 8
    fi
fi

if [ -e $MAIN_SRC.pdf ]; then
 # This is Mac specific command
    open -a Preview $MAIN_SRC.pdf
fi
