#!/bin/sh
# Remove working files from last run.
#
USAGE="
# USAGE ############## USAGE ############## USAGE ############## USAGE ##############
# Clean up all the outputs of latex commands.
# Two scenarios: given a dir or given a file                                        #
# If a dir is given, all the outputs with certain extension will be cleaned out     #
# If a file name is given, all the files with certain extensions will be cleaned out#
# LIMITATIONS: the file names cannot contain space and must has extension names     #
#####################################################################################
"
clean(){
    if [ -d "$input" ]; then
        mainsrc="$input/*"
    elif [ -f "$input" ]; then
        mainsrc=${input%.*}
    elif [ -f "$input.tex" ]; then
        mainsrc=${input}
    else
        echo "Specify valid source file or directory"
        exit 1
    fi

    echo "Cleaning latex outputs '$mainsrc...'"
    rm -f $mainsrc.log \
           $mainsrc.aux \
           $mainsrc.bbl \
           $mainsrc.blg \
           $mainsrc.dvi \
           $mainsrc.idx \
           $mainsrc.ilg \
           $mainsrc.ind \
           $mainsrc.lof \
           $mainsrc.lot \
           $mainsrc.ps \
           $mainsrc.out \
           $mainsrc.brf \
           $mainsrc.pdf \
           $mainsrc.toc   2>/dev/null
}

cleanall(){
  input=$1
#  echo "$input"
  clean "$input"
  if [ -d "$input" ]; then
    for f in $input/*/; do
      cleanall ${f%/}
    done
  fi
}

if [ $# -gt 0 ]; then
  input="${BASH_ARGV[0]}"
  if [ ${input: -1} == / ]; then
    input=${input%?}
  fi
else
  input='.'
fi
cleanall "$input"
