#!/bin/sh
#
# A Bourne shell script file to compile the latex template.
# The test of exit code after the first latex command causes
# execution of the shell script to stop if there were unresolved
# errors (so one will not have to repeat the same steps four more
# times before the shell script ends).
#

#bin=$(cd $(dirname "$0") > /dev/null; pwd)
#PATH="$PATH:bin"
#
if [ $# -ge 1 ]; then
    MAIN_SRC="${1%.*}"
elif [ `ls -l *.tex|wc -l` -eq 1 ]; then
    filename=`ls *.tex`
    MAIN_SRC="${filename%.*}"
else
    echo "You have to specify the main source file '*.tex'"
    exit 11
fi

# Remove working files from last run.
#
rm -f $MAIN_SRC.log \
	*.aux \
	$MAIN_SRC.bbl \
	$MAIN_SRC.blg \
	$MAIN_SRC.dvi \
	$MAIN_SRC.idx \
	$MAIN_SRC.ilg \
	$MAIN_SRC.ind \
	$MAIN_SRC.lof \
	$MAIN_SRC.lot \
	$MAIN_SRC.ps \
	$MAIN_SRC.out \
	$MAIN_SRC.brf \
	$MAIN_SRC.pdf \
	$MAIN_SRC.toc	2>/dev/null

# Clear the screen.
#
clear

# Run latex, bibtex, and makeindex to create the output file
#
echo ""
echo "	First run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 2
	fi

if [ -e $MAIN_SRC.bib ]; then
    echo ""
    echo "	Run of BibTeX ..."
    echo ""
    bibtex $MAIN_SRC
    exitcode="$?"
    if test $exitcode -ne 0
      then
        exit 3
    fi
else
    echo "Skip running BibTeX."
fi

echo ""
echo "	Second run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 4
	fi
echo ""
echo "	Third run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 5
	fi
echo ""
echo "	Run of makeindex ..."
echo ""
makeindex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 6
	fi
echo ""
echo "	Fourth run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 7
	fi
echo ""
echo "	Fifth and last run of LaTeX ..."
echo ""
pdflatex $MAIN_SRC
exitcode="$?"
	if test $exitcode -ne 0
	  then
	    exit 8
	fi

if [ -e $MAIN_SRC.pdf ]; then
    open $MAIN_SRC.pdf
fi
