#!/bin/sh
# Check that files are referenced by at least one other file
#
USAGE="
# USAGE ############## USAGE ############## USAGE ############## USAGE ##############
#####################################################################################
"

exttest() {
  exts=(tex log aux bbl blg dvi idx ilg ind lof lot ps out brf pdf toc)
  for e in "${exts[@]}" ; do
    if [ ${e} = ${extname} ]; then
      return 1
    fi
  done
}

fcheck(){
# tex files: check if other tex file reference it
# other file types: check if a tex file reference it
# search for referencing files in the current or parent folders only
# non-referenced (standalone) files are printed
  file=$1
  dname=`dirname "${file}"`
  fname=`basename "${file}"`
  # get chars after the last '.' in the file name
  extname="${fname##*.}"
  if ! exttest $extname ; then
    return 0
  fi

  # while true ...
  while : ; do
    result=`2>/dev/null grep "$fname" ${dname}/*.tex`
    if [ ! -z "$result" ] || [ ${#dname} == 1 ] ; then
      break
    fi
    dname=`dirname "${dname}"`
  done
  if [ -z "$result" ] ; then
      echo "$file"
  fi
}

recursive_check(){
  path=$1
  for f in ${path}/* ; do
    if [ -f "$f" ] ; then
      fcheck "$f"
    elif [ -d "$f" ] ; then
      recursive_check "${f}"
    fi
  done
}

if [ $# -gt 0 ]; then
  path="${BASH_ARGV[0]}"
  # ${path: -1} -- last char of the string
  if [ ${path: -1} == / ]; then
  # get rid of the last char in path
    path=${path%?}
  fi
else
  path='.'
fi
recursive_check "$path"
